spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false